adds readme file and issue template for review
lenushealth/feedback pull request #1
Opened 2018-02-28 14:15 UTC by Philo

2018-02-28 15:41 UTC, lynchjames commented on .github/issue_template.md
> +* **I'm submitting ...**
Can we also include questions on this list?

2018-03-01 09:35 UTC, lynchjames requested changes
Pulling out questions specifically a little more.

2018-03-01 09:35 UTC, lynchjames commented on README.md
> +- better understand the features of the platform that you like (or dislike)
Can we mention asking questions here as well?

2018-03-01 09:35 UTC, lynchjames commented on .github/issue_template.md
> +* **I'm submitting ...**
Can we also include a question template?

2018-03-02 11:32 UTC, Philo commented
Updates readme and template with requested updates @lynchjames

2018-03-13 18:08 UTC, merged